### ISSUE TITLE
multilayer shows often cannot determine init time format

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1085]
A user reported often seeing

![init_time](https://user-images.githubusercontent.com/278728/126108048-00e61f98-0b28-4536-9538-91d927f23729.jpg)

**Comment by ReimarBauer** [comment]
From the user perspective it is difficult to destinguish if this is an enhancement or bug. It happens because of wrong server data. 
So at all that is not a bug in the client but we recognized that we can improve this.

Because of the current CIRRUS Campaign we solve this problem on the client site. 

From a developer perspective it can be a useablity bug or also an enhancement.

**Comment by joernu76** [comment]
I dislike the current solution, even though it was necessary for CIRRUS-HL.
I think we need to revisit the XML-parsing and think of the server also as "an enemy".
For the given problem, I believe that a *single* pop up per GetCapabilities request would be fine. Without such a pop-up window we will never know about such an error, because no one reads the log files, typically.

Desired state: Problems in the XML document should be communicated in a much more visible way than the log. Simple solution: *one* pop-up window per GetCapabilities-Button pressing for all errors with hint to look into the log for details.

We can solve this as well in develop, because the pressing issue has been addressed in stable.

Other opinions?

**Comment by ReimarBauer** [comment]
The solution needs to inform also on stored GetCapablities requests that some datasets are not accessible. 
The inactive grayed lines helps here, as the user usually don't know what a server should or can offer.

Anyway on adding a server that this has inclomplete or not useable data at all can also lead into discussions with the server owner. May be on incomplete we can show the info from the dataset itselfs with contact informations. Ideally the user gets in contact to the server provide and the problem gets solved.

For a server with none valid data, the server should be purged on request from the multilayer window.

**Comment by ReimarBauer** [comment]
reopen when this happens again
