### ISSUE TITLE
refactor for os Darwin ctrl to meta key

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1158]
on Mac the ctrl key is the meta key, we have to replace all occurencies of the ctrl key only for that OS in all UI elements.

**Comment by aravindm711** [comment]
I think shortcuts for quit(ctrl+q/cmnd+q), close window(ctrl+w/cmnd+w), save, save as, open should remain ctrl+.../cmnd+... because they don't create a problem like ctrl+h does. We can just translate ctrl to meta for opening views, which is reasonable because these are features that we've included unlike the ones that are standard in all softwares. Or we could convert the view shortcuts to alt+... in which case we wouldn't need to translate any shortcut to any OS.

what do you think @ReimarBauer ?

**Comment by ReimarBauer** [comment]
Good idea, we should find a solution which does not mean a special case. 

It is on linux the ALT key which is used to access all underlined functions. E.g. in Help the H is underlinded. And Alt + h opens the help menu, ALT + f opens the file menu and so on.

Another Option is to use not Ctrl + h, just exchanging the h, by another character.  This only breaks the hidden logic of first letter of the name. It is not exact this way because +t is also first letter of Table and Top . 

I woluld go for Ctrl + l shown as (Ctrl + L) L could mean Landscape so it is something which can be recalled.

**Comment by aravindm711** [comment]
Definitely finding an alternative for h would be the best solution. ctrl+l (landscape) sounds good to me.

**Comment by ReimarBauer** [comment]
I'm back from vacation. Do you have time to work on this?

**Comment by aravindm711** [comment]
I'm working on some things as of now. I can include this as well.

**Comment by aravindm711** [comment]
Ctrl + L is taken up by Linearview shortcut. Shall I change all the view shortcuts to Alt+... ? @ReimarBauer

**Comment by ReimarBauer** [comment]
Interesting, I had a closer look.

ALT is already set :) e.g. ALT + V openes the Views. Topview is ALT + V T

![now](https://user-images.githubusercontent.com/278728/135446740-819ca34c-4a8a-4c0c-b23a-ff2ef1c55d09.png)

We have currently two keys 
(ALT + V) T and CTRL +H


How is it when we just repeat underlined keys? When the menu is opened a T starts topview.


Alt + T
Alt + S
Alt + A
Alt + L 

so with ALT we use same shortcuts.

**Comment by aravindm711** [comment]
Which one should I change them to? @ReimarBauer 

Alt + H
Alt + V
Alt + T
Alt + L

or 

Alt + T
Alt + S
Alt + A
Alt + L

**Comment by ReimarBauer** [comment]
if possible the last one. This is then the same letter which QT itselfs reserves in that menu. I think they are not occupied.

**Comment by aravindm711** [comment]
I just remembered we use Alt + S for shortcut window. We are currently translating only the view shortcuts to meta + ... on mac, and other platforms can continue using the ctrl + ... shortcuts. Since other shortcuts like cmnd/ctrl + s, S, o, n do not make a problem, I think we can continue with the existing shortcuts, which is a rather simple solution.

**Comment by ReimarBauer** [comment]
ok
