### ISSUE TITLE
test for finding leftover merge marker

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1181]
We should add at a test for looking on leftover merge marker one of 

```
<<<<<<< 

>>>>>>>
```
or other common symbols

**Comment by swsrkty** [comment]
Hi @ReimarBauer, I would like to take up this issue.

**Comment by ReimarBauer** [comment]
HI @sr1j you have it. Thanks.

**Comment by swsrkty** [comment]
Hi @ReimarBauer . I think instead of using tests, we can use a git pre-commit hook to find leftover merge markers before every commit. I've found two ways we can do that at MSS:

1. Manually add a pre-commit hook using this [tutorial](https://mranderson.nl/2020/10/25/how-to-share-git-hooks/). This method requires the developer to follow some steps on their system to configure git hooks.

2. Install git-hooks using the [pre-commit](https://pre-commit.com/) framework. This method is more developer friendly as there are no configuration steps.

We can write a test too by using a modified code from [this pre-commit hook](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_merge_conflict.py) in the pre-commit-hooks repo.

I think using pre-commit (2nd option) is better because it would check for the merge markers before commiting. If we use a test, the developer would only be notified of the leftover merge markers if they run the tests locally or when they open a PR and the CI is triggered. What do you think is the better option? Thanks!

**Comment by ReimarBauer** [comment]
pre-commit sounds the way we should go. Thx for pointing on this. Please check if this also works by the mamba command. We move from miniconda to mintforge or mambaforge.

**Comment by swsrkty** [comment]
Hi @ReimarBauer, while going through the instructions to install pre-commit, I realised that the user needs to run the command:
```
pre-commit install
```
so that the pre-commit hook gets installed at their `.git/hooks` directory and it gets invoked before every commit. For that we need to specify the command in the README.

Do you think tests (which would run when the user open a PR) are better than making the user run the command?

**Comment by ReimarBauer** [comment]
Moin @sr1j 

I think we should describe https://mss.readthedocs.io/en/stable/development.html with a new section similiar to Setting up a git remote this as a feature for developers.  The rst docs are below docs/.
The knowledge about pre.commit can be useful, but I think at same time for a newcomer this  step should not mandatory to send a PR to us. This is maybe to much hastle.

A unit test will help to not oversee a merge marker. A merge problem did not occure often. If a test is not successful, no further explanation is required.

**Comment by swsrkty** [comment]
Moin @ReimarBauer,

- I put some merge conflict markers in some files and tried running the tests, and the tests failed with syntax error. So I think we don't need a test for finding merge markers because the existing tests would always fail with a syntax error.
- I found out that `pre-commit` works in case of commiting and merging, but not in rebasing. For rebasing to work, we need to create a new repository with a  custom hook. I tried out pre-push hook, which would detect leftover marker before pushing.

What do you think? Can we go with the pre-push hook? This is how it would look like:

```
❯ git push origin feature
check for merge conflicts................................................Failed
- hook id: check-merge-conflict
- exit code: 1

Merge conflict string "<<<<<<< " found in mslib/msui/aircrafts.py:34
Merge conflict string "=======
" found in mslib/msui/aircrafts.py:36

error: failed to push some refs to 'https://github.com/sr1j/MSS.git'
```

**Comment by ReimarBauer** [comment]
Moin @sr1j 
I thought about it for a while. 
a) If a merge conflict is not noticeable, we rather have too few tests and should fix that.
b) Everything you say is correct. However, the effort is quite large to catch something that should not occur. The exchange of ideas has helped to realize this.
c) If we encounter a similar problem later we will be able to build on this. But for this question I think the effort is too big. We leave it with this documentation.

**Comment by swsrkty** [comment]
Sounds good, @ReimarBauer. In the future we can think about installing this along with other hooks such as to check commit messages or for finding white spaces.
