### ISSUE TITLE
Log, Autolog and Nonlinear Plotting not possible

### ISSUE THREAD

**Issue by crolf** [Open-MSS/MSS#1573]
I get a 404 error for just changing the plotting style of one variable to one of the following plotting styles "Log, Autolog and Nonlinear":

`ERROR:
<class 'requests.exceptions.HTTPError'>
404 Client Error: NOT FOUND for url: https://forecast.fz-juelich.de/phileas/?version=1.1.1&request=GetMap&layers=CLaMS_PL.mole_fraction_of_water_vapor_in_air_pl&styles=+nonlinear+&width=930&height=465&srs=EPSG%`

The standard plotting styles "Default" and "Auto" are working fine. The Error occurs on Side as well as Top View.

**Comment by joernu76** [comment]
The issue was caused by an incorrectly executed hacky patch in the mswms_settings.py, which overrides some internal functions of mswms to change some colourmaps (originally for the ACCLIP campaign).
Only the develop branch offers a more elegant way of achieving this, but 7.0.x does not. BTW, the config will break upon the upgrade to 7.1+.
However, I fixed my hacky patch and it seemingly works for the time being.
