### ISSUE TITLE
develop: Crash for viewing description for operations without admin rights

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#2005]
This affects only the develop branch.
```
Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 527, in view_description
    creator_name = _json["username"]
KeyError: 'username'
CRITICAL: MSS Version: 8.2.0
CRITICAL: Python Version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
CRITICAL: Platform: Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 527, in view_description
    creator_name = _json["username"]
```

**Comment by ReimarBauer** [comment]
@joernu76 that works for me in the released version.

I tried with a cirrus flight where I am having collaborator role

**Comment by ReimarBauer** [comment]
Please prefix issues with develop, if that happens there. I did this already.

**Comment by ReimarBauer** [comment]
This likly needs a patch in the released server code
```
iff --git a/mslib/mscolab/file_manager.py b/mslib/mscolab/file_manager.py
index f6d817b1..59c3c7d5 100644
--- a/mslib/mscolab/file_manager.py
+++ b/mslib/mscolab/file_manager.py
@@ -430,7 +430,8 @@ class FileManager:
         return users
 
     def fetch_operation_creator(self, op_id, u_id):
-        if not self.is_admin(u_id, op_id) and not self.is_creator(u_id, op_id):
+        if (not self.is_admin(u_id, op_id) and not self.is_creator(u_id, op_id)
+                and not self.is_collaborator(u_id, op_id)):
             return False
         current_operation_creator = Permission.query.filter_by(op_id=op_id, access_level="creator").first()
         return current_operation_creator.user.username
```
or without a limitation, depends if there is a risk to show more information to someone with viewer role on an external application.

But in 8.X we don't have this kind of description

**Comment by joernu76** [comment]
If one can "see" the operation one should be able to find out who the creator is.
For example in gitlab, I am able to see all members and their roles when I am only a developer, which I think is similar to collaborator.
If we could update the server (i.e. stable branch), this'd be preferable, but as the feature of viewing the owner via description is only in develop, this'd be sufficient (while a patch to stable'd be appreciated it is by no means necessary).

In practice, there is a phileas operation, where the rights are not properly propagated and I cannot find out who the owner is to remedy the issue. "F07_Ferry...". Maybe you can help there and fix the rights/archive the flight?

**Comment by ReimarBauer** [comment]
It is for stable an enhancement, which just means we go for a minor release and not a patch level bug fix release.
Dependent on the PR to stable or develop we have to shift the milestone, change the label of the issue etc.. That's all.

Because of the running campaign where users are using an unstable development branch we should not oversee that we usually use the issue tracker for indicating differences between released versions.

When we have a "bug" for 9.0 which is not released it is at the time of the release not a bug.  It was ongoing development work.  I have no better solution than currently indicating this in the name of the issue by a prefix "develop".

**Comment by joernu76** [comment]
OK, so bugs in develop are not bugs, but what? 

I mentioned "develop" in the text, but not the title (which is a better practice; I do not think we have been doing that consistently so far; I am uncertain whether that is a good idea or whether we should use "tags" to differentiate).

**Comment by ReimarBauer** [comment]
I always look from the point of a released version based on stable.


I would prefer to use the title prefix, because we have to destinguish between improvements of the current stable and also bug fixes for stable. A release is always done on the stable branch. 

Later we will merge develop to stable the game continues with a higher release string. But we still have stable for releases and develop for working.

We want to take care and communicate what we found in develop until it gets released. prefix with develop means it is to be considered separately to current release.  This is the important key, independent what label is choosen.

Without a prefix it means, enhancement or bugfix of current stable. 

At the release time this is important to destinguish, otherwise I would comunicate bug fixes which aren't because based on something unreleased.

**Comment by kedar1251090306** [comment]
Interested for GSoC 2026 prep—working on a PR!

**Comment by ReimarBauer** [comment]
Hi @kedar1251090306 
this is done and we don't take part at GSoC,see  our [blog post](https://open-mss.github.io/gsoc/stepping/back/for/now/2025/11/25/stepping_back_from_gsoc_for_now.html)
