### ISSUE TITLE
flake8 in develop gets sloppy

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2374]
I recognized that his was not show as failure by our flake8 checket.

https://github.com/Open-MSS/MSS/pull/2373#discussion_r1606099190

**Comment by matrss** [comment]
Yes, because flake8 is only run for mslib/ and tests/. I don't know why this decision was made, I've already noted that this is not great in https://github.com/Open-MSS/MSS/issues/2145#issuecomment-1921162556. We should enable it for the entire repository, including e.g. tutorials/, docs/, setup.py, etc.

**Comment by matrss** [comment]
And we should revisit the list of globally ignored lint rules and check if we really want to skip them or if they would make sense to enable.

**Comment by ReimarBauer** [comment]
I think we should change flake8 check for the whole dir. I guess after adding tutorials we forget to adopt the rules and we thought only on dir levels. docs/conf.py was initially autogenerated 

We have to check with Joern for the all  lint rules option.
