### ISSUE TITLE
mscolab chat upload/download  did not use configured "filepicker_default": "fs"

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#638]
This is similar to
https://github.com/Open-MSS/MSS/issues/636

if we configure in mss_settings.json the "fs" filepicker this is currently for mscolab chat upload/download ignored

To verify this you need a config file mss_settings.json to be stored in $HOME/.config/mss

{
 "filepicker_default": "fs"
}

mss_qt.get_open_filename needs to be used

source to look at
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab_project.py

please check if the test needs a fix too

**Comment by aravindm711** [comment]
I have been assigned to issue #636 and since this is a similar issue, can i provide the fix?

**Comment by aravindm711** [comment]
Since the existing implementation for chat upload feature gets both file_path and file_name as return value from the qt filedialog https://github.com/Open-MSS/MSS/blob/stable/mslib/msui/mscolab_project.py#L237, but https://github.com/Open-MSS/MSS/blob/stable/mslib/msui/mss_qt.py#L78 only returns the file_path. It makes sense to use getOpenFileNameAndFilter method from fslib.fs_filepicker module. Do you have any suggestions on how to proceed with this?
