### ISSUE TITLE
Missing Code of conduct and Contributing documents

### ISSUE THREAD

**Issue by BobinMathew** [Open-MSS/MSS#643]
Hi, I see that your project don't have a Code of conduct.md and Contributing.md file
would you like me to Propose one for your team?
It will make your community profile stronger.

**Comment by ReimarBauer** [comment]
We are new on github, thx for the hint. Please share a link.

**Comment by Aspie96** [comment]
Note, @ReimarBauer.

I know this issue is old.

I am writing this just because it seems you might have learned about the CC only trough this issue, so you may not be aware of this.

Please know that the document, while very popular, is highly controversial. It has been at the center of many controversies (such as in the Linux Kernel, when some contributors thretened to revoke the license when it got imposed upon them. Luckly, revoking the GPL is likely legally impossible).

Because of American culture it is supported by many large companies and, while contributors often do not want it, maintainers adopt it, partly to avoid being villified (which has happened to those refusing to adopt it, in some instances).

The Contributor Covenant comes as a pledge, meaning that open source contributors are forced to accept a pledge in order to be able to contribute code, something that would be recognized as unreasonable in most other contexts.

It is not useful for projects, it is merely a political tool for the author. Indeed, the author recognizes it as a political tool: https://twitter.com/CoralineAda/status/1041465346656530432. Why does GitHub support this document? It's PR: https://twitter.com/CoralineAda/status/1194702830495510529

A code of conduct is not a necessary file, nor is it necessary to ask contributors to make a pledge before giving their code away for free. There is no real evidence that it is useful and there are many reasons to believe it is harmful. In addition, even the Contributor Covenant website itself advises against adopting it unless you have the resources to moderate and enforce it: https://www.contributor-covenant.org/

As a leader you are responsible for the safe, fair, and transparent enforcement of your community’s code of conduct. A code of conduct without such enforcement sends a false signal that a community is welcoming and inclusive, which can have a disastrous impact on marginalized or otherwise vulnerable people.

In essence, if someone else misbehaves and you don't have the resources to moderate in that moment (maybe because you are the only maintainer), then you are morally responsable for the violation of the pledge.

The Contributor Covenant is not a standard (not de jure, nor de facto), it is merely an unfortunate trend.

I don't want to start a fight. You have the right to have this, it's your repo. I understand I have never contributed anything, I'm here in peace. Just evaluate whether you should reconsider this, given the additional information.

Note that the "community profile" is just a GitHub thing. It doesn't mean your project is better in any way.
