### ISSUE TITLE
Descriptive titlestring not added in vertical sections (missing in mpl_vsec.py _latlon_logp_setup)

### ISSUE THREAD

**Issue by gisi90** [Open-MSS/MSS#694]
Just realized that descriptive title string is no longer added in vertical sections. Looks look some lines are missing in mpl_vsec.py when compared to the older version:

old version:
![grafik](https://user-images.githubusercontent.com/54586339/109628694-55f3d300-7b43-11eb-9181-f498f3cca1be.png)

new version:
![grafik](https://user-images.githubusercontent.com/54586339/109628741-660bb280-7b43-11eb-85a6-3b4c181bdca2.png)

**Comment by joernu76** [comment]
Related to issue (and fix) #162

**Comment by joernu76** [comment]
A current plot of stable MSS-UI and the SouthTrac server looks like this:
![image](https://user-images.githubusercontent.com/28449201/109660255-f01a4200-7b68-11eb-8524-bd2a3631656d.png)

There is a title (by UI) above the layer. The box within the layer has been removed because it was redundant to the title. There were never boxes for horizontal plots. There is more discussion in #162, but I think we thought it would be more consistent and less redundant in this fashion.

What is the use case for having the title (additionally/exclusively?) within the layer?

**Comment by gisi90** [comment]
Ah, ok. First, I thought it was removed on purpose but then I saw that the box is still there for the horizontal plots  in the lower left corner? 

I agree that there is no point in adding the same information twice. It's just that the Layer-name in the selection is the same as the title outside of the box and if more than 2 variables are plotted (e.g. addition T and Theta, CIWC, CLWC) we used to add this information in the inner box. Maybe this long "titlestring" can be used as title instead of the layer-name?

**Comment by joernu76** [comment]
There is also a "description" for plots, where you can put arbitrary text in. This is severly underused.... See the box in the lower left corner of my figure.
For complex plots of mine, I put a proper "paper-like caption" into the "abstract" and it appears in said box.

It is always possible to put arbitrary stuff *within* the plotting class, as happens for some of Marcs old HSEC plots (not sure about the current state). But we removed the code to *necessarily* add this info to *all* vertical layer plots. I would suggest to move/implement such info to the abstract where currently missing instead of re-adding the box. If desired for certain plots, this should be done in the plotting class, not in the "general" code section.

Does this make sense?

**Comment by gisi90** [comment]
Yup, makes sense and thanks for pointing to the description window. For the horizontal plots, the box was moved to the styles as you said (this is why I still have them). So the whole titlestring-thing/plot title can be removed from _latlon_logp_setup. It then only needs orography as input.

**Comment by joernu76** [comment]
I'll prepare a merge request doing that and moving some title stuff to the abstract.
