### ISSUE TITLE
Capability document not updated?

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#805]
Steps to reproduce the problem.
develop branch. 
1. getCapabilties of a server
2. change server setup
3. getCapabilties of the same server

"view" should show the new capabilities.
Currently, it shows the first ones.

**Comment by ReimarBauer** [comment]
This happened likly with storing the "styles" we now store the whole capabilities.
 
The problem is that also the server datafiles changes from day to day.  
We had a similiar problem in the past as we had used a server site caching, see https://github.com/Open-MSS/MSS/issues/268 

For these kinds of updated data we don't have tests yet.

**Comment by ReimarBauer** [comment]
We need a backport of this to stable.
