### ISSUE TITLE
standard figure file name in the case of multilayering

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#855]
If multilyering is chosen, the standard file name suggested upon saving the figure should be named by the main chosen variable "1". This is currently not the case.

**Comment by Marilyth** [comment]
As these two are related. Do you also suggest the title of the plot to represent the "1" layer instead of the last one?
Currently the highest numerical priority is chosen both for the title of the plot and filename for saving it.

![Screenshot at 2021-04-29 14-35-08](https://user-images.githubusercontent.com/19623152/116551805-9203a400-a8f8-11eb-86d5-16f371efe67b.png)

**Comment by jgrooss** [comment]
Yes. I just reckognised, that also the title is given from the overlay figure not from the "main" figure. It would be much more logical to me to have the priority 1 giving the figure name and title.
