### ISSUE TITLE
WMS server provides incorrect figure in the case of  dataset update  

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#886]
In the calculations for scientific flight planning, it may happen, that a datafile is updated, having the identical filename, but more timesteps. It seems that the server does not check for the update and returns false figures by not correctly interpolating within the data. After re-starting the user interface and clearing the cache, a correct figure is shown.
It is not clear, whether this is a problem of the user interface or of the server.
wrong figure:
![topview_contour_250 0_bug](https://user-images.githubusercontent.com/32653190/116783936-d9716800-aa91-11eb-80d5-5d50e3b635d7.png)
correct figure:
![topview_contour_250 0_correct](https://user-images.githubusercontent.com/32653190/116783944-e0987600-aa91-11eb-972b-008318916da5.png)

**Comment by jgrooss** [comment]
In the shown case, the server was not re-started.

**Comment by ReimarBauer** [comment]
Please retry with emptied cache and afterwards with Cache disabled from the UI.

**Comment by jgrooss** [comment]
Reproduction of the error as follows:
There are two data sets, 20210501_00_clamsice_forecast.pl.nc.short (5 timesteps) and
20210501_00_clamsice_forecast.pl.nc.long (11 timesteps) including those of the short data set.
The data sets are copied to icg1805:/private.scratch/icg122/mssdata
On the server, also the data set from previous day is present.


1. copy short data set (5 timesteps) to the server 
2. start mss user interface
3. untick use cache
4. retrieve one figure (cloud_ice_mixing_ratio, fixed log scale, init 05-01 0:00 UT, valid, 05-03 0:00UT, 300hPa) 
   -> correct figure
5. copy large data set to the server (overwriting the short data set)
6. switch to level 250 hPa and retrieve  
   -> wrong figure
7. start new top view panel in same session
8. retrieve identical figure 
   -> correct figure

**Comment by ReimarBauer** [comment]
At the time the server gets a new file replacing the old one the client has to refresh getCapabilities. Thats in the example in 4. and 8.  

We could think about to request on each retrieve a verification that the "getCapabilities" data of the client is outdated compared to the servers version.

When it is outdated retrieve happens after the update of GetCapabilities.

**Comment by ReimarBauer** [comment]
This described behaviour is by design. 

An optional parameter updatesequence of the WMS standard can be used to enhance this behaviour.

updatesequence

Description: (Optional) The server may include an UpdateSequence value in its service metadata. If present, this value should be increased when changes are made to the Capabilities (e.g. when new maps are added to the service). The client may include this parameter in its GetCapabilities request.

**Comment by joernu76** [comment]
What about the second TopView? Was the get_capabilities button pressed before retrieving the map?

The server only checks for changed files upon a get_capabilities call. This is typically sufficient for our "normal" use case of only "adding" and "removing" files. "Changing" was, so far, not high on our agenda.
This is a design decision to reduce the load on the server.

We could, probably, add a check that an accessed file has not been modified. The default access class cannot do that (because it is stateless and has no notion of its administrated files except their existance), but the cached access class could check for modification time... 
We could use the CachedAccess class as default as well. We use it rather successfully operationally since three years now...
