### ISSUE TITLE
mss -v initialises skyfield

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#950]
when we ran mss -v we do load a lot modules which might be not needed to show the version

involved are: topview - remotesensing_dockwidget - skyfield/api.py - skyfield/iokit.py

**Comment by ReimarBauer** [comment]
We should add this data by 
https://github.com/brunobord/skyfield-data

**Comment by joernu76** [comment]
Loading these modules should not trigger the download of any (substantial) data.
Due to the lack of "interfaces" or similar in Python I do not see how to *not* load the majority of msui when calling the main program unless we start importing stuff in the __init__ functions...? I am not aware that this is good style...?

**Comment by joernu76** [comment]
Propose to close this.
