### ISSUE TITLE
RuntimeWarning: invalid value encountered

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#973]
```
INFO: Sending polling GET request to http://localhost:8083/socket.io/?transport=polling&EIO=3&sid=1d61d8e6ae21454ba8f17f52f6297380
/home/user/PycharmProjects/mss/mslib/msui/mpl_pathinteractor.py:77: RuntimeWarning: invalid value encountered in double_scalars
  r = (np.dot(p - l1, l2 - l1) / np.linalg.norm(l2 - l1) ** 2)
```

**Comment by joernu76** [comment]
Context? Probably l1==l2 and there is a division by zero? 
Is there a user-discernible problem?

numpy is generally throwing a lot of similar warnings, which are really annoying to deactivate (because doing it right adds a lot of code). See e.g. https://stackoverflow.com/questions/29347987/why-cant-i-suppress-numpy-warnings
